---
jobs:
  - name: deploy
    serial: true
    plan:
      - get: automation
      - get: config
      - get: image
      - task: deploy
        image: image
        config:
          platform: linux
          inputs:
            - name: automation
            - name: config
          params:
            COLOR: ((color))
            ENV_NAME: sandbox
            VERSION: ((component-version))
          run:
            path: sh
            args:
              - -ec
              - |
                echo "Deploying..."
                echo "color:    '${COLOR}'"
                echo "env_name: '${ENV_NAME}'"
                echo "version:  '${VERSION}'"
                sleep 5
                echo OK!

resources:
  - name: automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-automation.git
      branch: master
      private_key: ((github-private-key))

  - name: config
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-config.git
      private_key: ((github-private-key))

  - name: image
    type: registry-image
    icon: docker
    source:
      repository: busybox