---
jobs:
  - name: deploy
    serial: true
    plan:
      - get: trigger
        trigger: true
      - get: automation
      - get: config
      - get: image
      - task: deploy
        image: image
        config:
          platform: linux
          inputs:
            - name: automation
            - name: config
          params:
            COLOR: ((color))
            ENV_NAME: (env_name)
            VERSION: ((component-version))
          run:
            path: sh
            args:
              - -ec
              - |
                echo "Deploying..."
                echo "color:    '${COLOR}'"
                echo "env_name: '${ENV_NAME}'"
                echo "version:  '${VERSION}'"
                sleep 5
                echo OK!

resources:

  - name: trigger
    type: semver
    source:
      driver:      git
      uri:         git@github.com:gstackio/gk-pipelines-compass.git
      branch:      master
      file:        triggers/deploy-((env_name))-concourse-training
      private_key: |
        ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"
      initial_version: 1.0.0

  - name: automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-automation.git
      branch: ((source_branch))
      private_key: ((github-private-key))

  - name: config
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-config.git
      private_key: ((github-private-key))

  - name: image
    type: registry-image
    icon: docker
    source:
      repository: gstack/gk-ops
