---
jobs:
  - name: repipe-sandbox
    serial: true
    plan:
      - in_parallel:
          - get: automation
            trigger: true
          - get: config
            trigger: true
          - get: image

      - task: prepare-pipeline
        image: image
        params:
          ENV_NAME: sandbox
        file: automation/ci/repipe/tasks/prepare-pipeline.yml

      - set_pipeline: deploy-sandbox
        file: prepared-pipeline/assembled-pipeline.yml
        var_files:
          - automation/ci/deploy-infra/config/versions.yml
          - config/sandbox/settings.yml
        vars:
          env_name: sandbox
          source_branch: master
          next_env: staging

      - put: trigger-sandbox
        params: { bump: patch }

  - name: repipe-staging
    serial: true
    plan:
      - in_parallel:
          - get: staging-automation
            trigger: true
          - get: config
            trigger: true
          - get: image

      - task: prepare-pipeline
        image: image
        input_mapping:
          automation: staging-automation
        params:
          ENV_NAME: staging
        file: staging-automation/ci/repipe/tasks/prepare-pipeline.yml

      - set_pipeline: deploy-staging
        file: prepared-pipeline/assembled-pipeline.yml
        var_files:
          - staging-automation/ci/deploy-infra/config/versions.yml
          - config/staging/settings.yml
        vars:
          env_name: staging
          source_branch: staging
          next_env: prod

      - put: trigger-staging
        params: { bump: patch }

  - name: repipe-prod
    serial: true
    plan:
      - in_parallel:
          - get: automation
            resource: prod-automation
            trigger: true
          - get: config
            trigger: true
          - get: image

      - task: prepare-pipeline
        image: image
        params:
          ENV_NAME: prod
        file: automation/ci/repipe/tasks/prepare-pipeline.yml

      - set_pipeline: deploy-prod
        file: automation/ci/deploy-infra/pipeline.yml
        var_files:
          - automation/ci/deploy-infra/config/versions.yml
          - config/prod/settings.yml
        vars:
          env_name: prod
          source_branch: prod

      - put: trigger-prod
        params: { bump: patch }

resources:
  - name: automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-automation.git
      branch: master
      private_key: ((github-private-key))

  - name: staging-automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-automation.git
      branch: staging
      private_key: ((github-private-key))

  - name: prod-automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-automation.git
      branch: prod
      private_key: ((github-private-key))

  - name: trigger-sandbox
    type: semver
    source:
      driver:      git
      uri:         git@github.com:gstackio/gk-pipelines-compass.git
      branch:      master
      file:        triggers/deploy-sandbox-concourse-training
      private_key: ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"
      initial_version: 1.0.0

  - name: trigger-staging
    type: semver
    source:
      driver:      git
      uri:         git@github.com:gstackio/gk-pipelines-compass.git
      branch:      master
      file:        triggers/deploy-staging-concourse-training
      private_key: ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"
      initial_version: 1.0.0

  - name: trigger-prod
    type: semver
    source:
      driver:      git
      uri:         git@github.com:gstackio/gk-pipelines-compass.git
      branch:      master
      file:        triggers/deploy-prod-concourse-training
      private_key: ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"
      initial_version: 1.0.0

  - name: config
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-config.git
      branch: master
      private_key: ((github-private-key))

  - name: image
    type: registry-image
    icon: docker
    source:
      repository: gstack/gk-ops
