---
jobs:
  - name: repipe-sandbox
    serial: true
    plan:
      - in_parallel:
          - get: automation
          - get: config
          - get: image

      - task: prepare-pipeline
        image: image
        params:
          ENV_NAME: sandbox
        file: automation/ci/repipe/tasks/prepare-pipeline.yml

      - set_pipeline: deploy-sandbox
        file: prepared-pipeline/assembled-pipeline.yml
        var_files:
          - automation/ci/deploy-infra/config/versions.yml
          - config/sandbox/settings.yml
        vars:
          env_name: sandbox
          next_env: staging

  - name: repipe-staging
    serial: true
    plan:
      - in_parallel:
          - get: staging-automation
          - get: config
          - get: image

      - task: prepare-pipeline
        image: image
        input_mapping:
          automation: staging-automation
        params:
          ENV_NAME: staging
        file: automation/ci/repipe/tasks/prepare-pipeline.yml

      - set_pipeline: deploy-staging
        file: prepared-pipeline/assembled-pipeline.yml
        var_files:
          - automation/ci/deploy-infra/config/versions.yml
          - config/staging/settings.yml
        vars:
          env_name: staging
          next_env: prod

  - name: repipe-prod
    serial: true
    plan:
      - in_parallel:
          - get: automation
            resource: prod-automation
          - get: config
          - get: image

      - task: prepare-pipeline
        image: image
        params:
          ENV_NAME: prod
        file: automation/ci/repipe/tasks/prepare-pipeline.yml

      - set_pipeline: deploy-prod
        file: automation/ci/deploy-infra/pipeline.yml
        var_files:
          - automation/ci/deploy-infra/config/versions.yml
          - config/prod/settings.yml
        vars:
          env_name: prod

resources:
  - name: automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-automation.git
      branch: master
      private_key: ((github-private-key))

  - name: staging-automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-automation.git
      branch: staging
      private_key: ((github-private-key))

  - name: prod-automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-automation.git
      branch: prod
      private_key: ((github-private-key))

  - name: config
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/deploy-config.git
      branch: master
      private_key: ((github-private-key))

  - name: image
    type: registry-image
    icon: docker
    source:
      repository: gstack/gk-ops
